GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsIm5hbWUiOm51bGwsImVtYWlsIjoibWF0dGhld0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxODA4NDk2OCwiZXhwIjoxNzE4MDg0OTgzfQ.ElzEa9R2SeqzjY9kCi4KJ4_-qDCC5qwIzh67pciUqRQ

###

POST  http://localhost:5000/users
Content-Type: application/json

{
"name" : "Matthew ",
"email" : "email@gmail.com",
"password" : "123456",
"confPassword" : "123456"
}
    
###

POST  http://localhost:5000/login
Content-Type: application/json

{
    "email" : "matthew@gmail.com",
    "password" : "12345"
}


###

GET  http://localhost:5000/token

###
DELETE  http://localhost:5000/logout